name: Workflow Test
on: push
jobs:
  Test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
