name: Workflow Test
on: push
jobs:
  Test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - run: make test
      - run: make lint
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test      
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
